// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    WalletConnectButton: typeof import('./components/WalletConnectButton.vue')['default']
    WalletDisconnectButton: typeof import('./components/WalletDisconnectButton.vue')['default']
    WalletIcon: typeof import('./components/WalletIcon.vue')['default']
    WalletModalProvider: typeof import('./components/WalletModalProvider.vue')['default']
    WalletMultiButton: typeof import('./components/WalletMultiButton.vue')['default']
  }
}

export {}
